cc=clang++
flags=-O3 -std=c++11 -w
files= Menu.cpp gerenciadorIndividuos.cpp fileIO.cpp pilhaRegistros.cpp listaDeRegistrosWorstFit.cpp gerenciadorEspecies.cpp gerenciadorCapturas.cpp gerenciadorArvoreB.cpp
debug=-O0 -g -std=c++11
all:
	$(cc) $(flags) $(files) -o main
debug:
	$(cc) $(debug) $(files) -o main
