/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lp.view;

import java.util.Iterator;
import javax.swing.JOptionPane;
import lp.HotelAnimais.Animal;
import lp.HotelAnimais.Diaria;
import lp.HotelAnimais.Estadia;
import lp.HotelCachorros.Persistencia.BancoDeDados;

/**
 *
 * @author vanderson
 */
public class CheckOutView extends javax.swing.JFrame {

    /**
     * Creates new form CheckOut
     */
    public CheckOutView() {
        initComponents();
        preencherListaAnimais();
    }

    private void preencherListaAnimais() {
        animalList.removeAllItems();
        animalList.addItem("Selecione um");
        Iterator i = BancoDeDados.getInstance().getAnimais().iterator();
        while (i.hasNext()) {
            Animal animal = (Animal) i.next();
            if(BancoDeDados.getInstance().getEstadia(animal)!=null){
                animalList.addItem(animal.getNome());
            }
        }
    }

    private Animal getAnimal() {
        String sel = (String) animalList.getSelectedItem();
        if (sel != null && !sel.equals("Selecione um")) {
            return BancoDeDados.getInstance().getAnimal(sel);
        }
        return null;
    }

    private void realizaCheckOut(){
        Animal animal = getAnimal();
        Estadia estadia=BancoDeDados.getInstance().getEstadia(animal);
        int dias = estadia.getQuantidadeDias();
        double preco = Diaria.Grade.getPreco(estadia.getAcomodacao().getDimensao());
        preco = preco*(int)quantidadeDeDias.getValue();
        if(dias < (int)quantidadeDeDias.getValue())
              preco=preco*1.1;
        
        if(estadia!=null){
            estadia.getAcomodacao().sairEstadia();
            BancoDeDados.getInstance().getEstadias().remove(estadia);
            JOptionPane.showMessageDialog(null, "Check out realizado com sucesso! Valor: "+preco);
        }else{
            JOptionPane.showMessageDialog(null, "Animal está cadastrado, mas não está hospedado!");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        animalList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoAnimal = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        checkOutButton = new javax.swing.JButton();
        quantidadeDeDias = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Animal:");

        animalList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        animalList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalListActionPerformed(evt);
            }
        });

        infoAnimal.setColumns(20);
        infoAnimal.setRows(5);
        jScrollPane1.setViewportView(infoAnimal);

        jLabel2.setText("Informações:");

        checkOutButton.setText("Check-out");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        quantidadeDeDias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        jLabel13.setText("Quantidade de dias:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(animalList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidadeDeDias, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(checkOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(animalList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeDeDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkOutButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void animalListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalListActionPerformed
        Animal ani = getAnimal();
        if(ani!=null){
            infoAnimal.setText("Porte: "+ani.getPorte()+"\n"+
                    "Dono: "+ani.getDono().getNome()+"\n"+
                    "Segundo res.: "+ani.getResponsavel2().getNome());
        }
    }//GEN-LAST:event_animalListActionPerformed

   
    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        realizaCheckOut();
        this.dispose();
    }//GEN-LAST:event_checkOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CheckOutView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox animalList;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JTextArea infoAnimal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner quantidadeDeDias;
    // End of variables declaration//GEN-END:variables
}
