/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lp.view;

import java.awt.Color;
import java.util.Date;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;
import lp.HotelAnimais.Acomodacao;
import lp.HotelAnimais.AcomodacaoEstado;
import lp.HotelAnimais.Animal;
import lp.HotelAnimais.Diaria;
import lp.HotelAnimais.Dono;
import lp.HotelAnimais.Especie;
import lp.HotelAnimais.Estadia;
import lp.HotelAnimais.Porte;
import lp.HotelCachorros.Persistencia.BancoDeDados;
import lp.HotelCachorros.Persistencia.CadastroException;

/**
 *
 * @author vanderson
 */
public class CheckInView extends javax.swing.JFrame {

    /**
     * Creates new form CheckInView
     */
    private Animal animal = null;
    private Dono resp1, resp2 = null;

    public CheckInView() {
        initComponents();
        iniciarCores();
        preencherEspecies();
        animal = new Animal(null, null, Especie.Cachorro, Double.NaN, Double.NaN);
    }

    private void iniciarCores() {
        comprimentoAnimal.setBackground(Color.WHITE);
        alturaAnimal.setBackground(Color.WHITE);
        teleRes1.setBackground(Color.WHITE);
        teleRes2.setBackground(Color.WHITE);
        nomeAnimal.setBackground(Color.WHITE);
        nomeRes1.setBackground(Color.WHITE);
        nomeRes2.setBackground(Color.WHITE);
    }

    private void preencherEspecies() {
        especiesBox.removeAllItems();
        for (Especie e : Especie.values()) {
            especiesBox.addItem(e);
        }
    }

    private Porte calcPorte() {
        try {
            Porte p = Porte.Grande;
            cadastrarAnimal();
            Porte g = p.classificarPorte(animal);
            porteAnimal.setText(g.toString());
            animal.setPorte(g);
            return g;
        } catch (CadastroException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Não é permitido tal porte.");
            return null;
        }
    }

    private boolean cadastrarAnimal() {
        boolean res = true;
        try {
            animal.setAltura(Double.parseDouble(alturaAnimal.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite uma altura válida! Apenas números! Campo obrigatório.");
            alturaAnimal.setBackground(Color.red);
            alturaAnimal.setText("");
            res = false;
        }
        try {
            animal.setAltura(Double.parseDouble(comprimentoAnimal.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite uma altura válida! Apenas números! Campo obrigatório.");
            comprimentoAnimal.setBackground(Color.red);
            comprimentoAnimal.setText("");
            res = false;
        }
        if (res) {
            BancoDeDados.getInstance().getAnimais().add(animal);
        }
        return res;
    }

    private void instanciarDonos() {
        resp1 = new Dono(nomeRes1.getText(), teleRes1.getText());
        resp2 = new Dono(nomeRes2.getText(), teleRes2.getText());
    }

    private void cadastrarResponsaveis() {
        BancoDeDados.getInstance().getPessoas().add(resp1);
        BancoDeDados.getInstance().getPessoas().add(resp2);
        animal.setDono(resp1);
        animal.setResponsavel2(resp2);
    }

    private Acomodacao procurarPorAcomodacaoVaga(Porte p) {
        try {
            Set<Acomodacao> a = BancoDeDados.getInstance().getAcomodacoes();
            Iterator<Acomodacao> i = a.iterator();
            while (i.hasNext()) {
                Acomodacao acomodacao = i.next();
                if (acomodacao != null
                        && acomodacao.getEstado() == AcomodacaoEstado.Livre
                        && acomodacao.getDimensao() == p
                        && acomodacao.getEspecie() == animal.getEspecie()) {
                    return acomodacao;
                }
            }
            return null;
        } catch (Exception e) {
            System.err.println("procurar por acomodação falhou! " + e.getMessage());
            return null;
        }
    }

    private Estadia cadastraEstadia(Acomodacao acomodacao) {
        Estadia estadia = new Estadia(animal, acomodacao, new Date(System.currentTimeMillis()), (int) quantidadeDeDias.getValue());
        acomodacao.addEstadia(estadia);
        BancoDeDados.getInstance().getEstadias().add(estadia);
        return estadia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private boolean checaTelefones() {
        boolean res = true;
        try {
            Integer.parseInt(teleRes1.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No campo telefone digite apenas números!");
            teleRes1.setBackground(Color.red);
            res = false;
        }
        try {
            Integer.parseInt(teleRes2.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "No campo telefone digite apenas números!");
            teleRes2.setBackground(Color.red);
            res = false;
        }
        int tamanhoTele1 = teleRes1.getText().replaceAll(" ", "").length();
        int tamanhoTele2 = teleRes2.getText().replaceAll(" ", "").length();

        if (tamanhoTele1 != 8) {
            JOptionPane.showMessageDialog(null, "Digite um número de telefone com 8 caracteres!");
            teleRes1.setBackground(Color.red);
            res = false;
        }
        if (tamanhoTele2 != 8) {
            JOptionPane.showMessageDialog(null, "Digite um número de telefone com 8 caracteres!");
            teleRes2.setBackground(Color.red);
            res = false;
        }
        return res;
    }

    private boolean procuraNum(String nome) {
        boolean res = false;
        for (int i = 0; i < 10; i++) {
            res |= nome.contains("" + i);
        }
        return res;
    }

    private boolean checaNomes() {
        boolean res = true;
        if (nomeAnimal.getText().isEmpty()) {
            res = false;
            JOptionPane.showMessageDialog(null, "Nome do animal é um campo obrigatório!");
            nomeAnimal.setBackground(Color.red);
        }
        if (nomeRes1.getText().isEmpty()) {
            res = false;
            JOptionPane.showMessageDialog(null, "Nome do responsável é um campo obrigatório!");
            nomeRes1.setBackground(Color.red);
        }
        if (nomeRes2.getText().isEmpty()) {
            res = false;
            JOptionPane.showMessageDialog(null, "Nome do segundo responsável é um campo obrigatório!");
            nomeRes2.setBackground(Color.red);
        }

        if (procuraNum(nomeAnimal.getText())) {
            res = false;
            JOptionPane.showMessageDialog(null, "Nome do animal deve conter apenas letras!");
            nomeAnimal.setBackground(Color.red);
        }

        if (procuraNum(nomeRes1.getText())) {
            res = false;
            JOptionPane.showMessageDialog(null, "Nome do responsável deve conter apenas letras!");
            nomeRes1.setBackground(Color.red);
        }
        if (procuraNum(nomeRes2.getText())) {
            res = false;
            JOptionPane.showMessageDialog(null, "Nome do segundo responsável deve conter apenas letras!");
            nomeRes2.setBackground(Color.red);
        }



        return res;
    }

    private boolean checaDadosDigitados() {
        boolean res = true;
        res &= checaTelefones();
        res &= checaNomes();
        return res;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        checkinButton = new javax.swing.JButton();
        nomeRes1 = new javax.swing.JTextField();
        teleRes1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teleRes2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nomeRes2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nomeAnimal = new javax.swing.JTextField();
        comprimentoAnimal = new javax.swing.JTextField();
        alturaAnimal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        especiesBox = new javax.swing.JComboBox();
        porteAnimal = new javax.swing.JTextField();
        quantidadeDeDias = new javax.swing.JSpinner();

        jLabel10.setText("Especie:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        checkinButton.setText("Realizar check-in");
        checkinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinButtonActionPerformed(evt);
            }
        });

        nomeRes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeRes1ActionPerformed(evt);
            }
        });

        teleRes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleRes1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Responsável (1):");

        jLabel3.setText("Nome:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Telefone:");

        jLabel6.setText("Nome:");

        teleRes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teleRes2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Responsável (2):");

        nomeRes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeRes2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Animal:");

        jLabel8.setText("Nome:");

        jLabel9.setText("Especie:");

        jLabel11.setText("Comprimento:");

        jLabel12.setText("Altura:");

        jLabel13.setText("Quantidade de dias:");

        nomeAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nomeAnimalFocusLost(evt);
            }
        });

        comprimentoAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprimentoAnimalActionPerformed(evt);
            }
        });
        comprimentoAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comprimentoAnimalFocusLost(evt);
            }
        });

        alturaAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaAnimalActionPerformed(evt);
            }
        });
        alturaAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alturaAnimalFocusLost(evt);
            }
        });

        jLabel14.setText("Porte:");

        especiesBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        especiesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especiesBoxActionPerformed(evt);
            }
        });
        especiesBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                especiesBoxFocusLost(evt);
            }
        });

        porteAnimal.setEditable(false);
        porteAnimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                porteAnimalMouseEntered(evt);
            }
        });
        porteAnimal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                porteAnimalFocusGained(evt);
            }
        });

        quantidadeDeDias.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quantidadeDeDias, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teleRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomeRes2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nomeRes1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teleRes1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(porteAnimal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(comprimentoAnimal)
                                            .addComponent(nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(especiesBox, 0, 188, Short.MAX_VALUE)
                                    .addComponent(alturaAnimal))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(checkinButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(teleRes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(teleRes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(nomeAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(especiesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(comprimentoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alturaAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(porteAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(quantidadeDeDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(checkinButton)
                .addGap(9, 9, 9))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Diaria d = Diaria.Grade;
    private void checkinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinButtonActionPerformed
        iniciarCores();
        boolean ok = checaDadosDigitados();
        if (ok) {
            Porte porte = calcPorte();
            if (porte != null) {
                Acomodacao acomodacao = procurarPorAcomodacaoVaga(porte);
                if (acomodacao != null) {
                    boolean res = cadastrarAnimal();
                    if (res) {
                        instanciarDonos();
                        cadastrarResponsaveis();
                        Estadia estadia = cadastraEstadia(acomodacao);
                        JOptionPane.showMessageDialog(null, "Checkin realizado com sucesso na acomodacao número: " + acomodacao.getNum() + ". \n "
                                + " Valor da diária: " + d.getPreco(porte) + " reais. "
                                + "\n Valor para " + quantidadeDeDias.getValue() + " dias: "
                                + estadia.getValor());
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Não existe vagas livres para o porte " + porte.toString());
                }
            } else {
                JOptionPane.showMessageDialog(null, "O hotel não suporta animais desse porte!");
            }
        }
    }//GEN-LAST:event_checkinButtonActionPerformed

    private void teleRes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleRes1ActionPerformed
    }//GEN-LAST:event_teleRes1ActionPerformed

    private void nomeRes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeRes1ActionPerformed
    }//GEN-LAST:event_nomeRes1ActionPerformed

    private void teleRes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teleRes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teleRes2ActionPerformed

    private void nomeRes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeRes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeRes2ActionPerformed

    private void alturaAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaAnimalActionPerformed
    }//GEN-LAST:event_alturaAnimalActionPerformed

    private void especiesBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especiesBoxActionPerformed
    }//GEN-LAST:event_especiesBoxActionPerformed

    private void comprimentoAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprimentoAnimalActionPerformed
    }//GEN-LAST:event_comprimentoAnimalActionPerformed

    private void porteAnimalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porteAnimalMouseEntered
        
    }//GEN-LAST:event_porteAnimalMouseEntered

    private void nomeAnimalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nomeAnimalFocusLost
        animal.setNome(nomeAnimal.getText());
    }//GEN-LAST:event_nomeAnimalFocusLost

    private void especiesBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_especiesBoxFocusLost
        animal.setEspecie((Especie) especiesBox.getSelectedItem());
    }//GEN-LAST:event_especiesBoxFocusLost

    private void comprimentoAnimalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comprimentoAnimalFocusLost
        comprimentoAnimal.setBackground(Color.WHITE);
        try {
            animal.setComprimento(Double.parseDouble(comprimentoAnimal.getText()));
        } catch (NumberFormatException e) {
            comprimentoAnimal.setBackground(Color.red);
        }
    }//GEN-LAST:event_comprimentoAnimalFocusLost

    private void alturaAnimalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alturaAnimalFocusLost
        alturaAnimal.setBackground(Color.WHITE);
        try {
            animal.setAltura(Double.parseDouble(alturaAnimal.getText()));
        } catch (NumberFormatException e) {
            alturaAnimal.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_alturaAnimalFocusLost

    private void porteAnimalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_porteAnimalFocusGained
       calcPorte();
    }//GEN-LAST:event_porteAnimalFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckInView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CheckInView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alturaAnimal;
    private javax.swing.JButton checkinButton;
    private javax.swing.JTextField comprimentoAnimal;
    private javax.swing.JComboBox especiesBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nomeAnimal;
    private javax.swing.JTextField nomeRes1;
    private javax.swing.JTextField nomeRes2;
    private javax.swing.JTextField porteAnimal;
    private javax.swing.JSpinner quantidadeDeDias;
    private javax.swing.JTextField teleRes1;
    private javax.swing.JTextField teleRes2;
    // End of variables declaration//GEN-END:variables
}
