/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lp.view;

import java.util.Iterator;
import java.util.Set;
import lp.HotelAnimais.Acomodacao;
import lp.HotelAnimais.AcomodacaoEstado;
import lp.HotelAnimais.Especie;
import lp.HotelCachorros.Persistencia.BancoDeDados;
import lp.HotelAnimais.Porte;

/**
 *
 * @author vanderson
 */
public class ConsultaAcomodacaoView extends javax.swing.JFrame {

    /**
     * Creates new form ColsultaAcomodacaoView
     */
    public ConsultaAcomodacaoView() {
        initComponents();
        preencherFiltros();
        preencherAcomodacoes();
    }

    private void preencherFiltros() {
        preencherFiltroEspecie();
        preencherFiltroEstado();
        preencherFiltroPorte();

    }

    private void preencherFiltroEspecie() {
        filtroEspecie.removeAllItems();
        filtroEspecie.addItem("Todos");
        for (Especie e : Especie.values()) {
            filtroEspecie.addItem(e);
        }
    }

    private void preencherFiltroPorte() {

        filtroPorte.removeAllItems();
        filtroPorte.addItem("Todos");
        for (Porte e : Porte.values()) {
            filtroPorte.addItem(e);
        }

    }

    private void preencherFiltroEstado() {

        filtroEstado.removeAllItems();
        filtroEstado.addItem("Todos");
        for (AcomodacaoEstado e : AcomodacaoEstado.values()) {
            filtroEstado.addItem(e);
        }

    }

    private boolean checarNoFiltro(Acomodacao acomodacao) {
        if (filtroEstado.getSelectedItem()!=null && filtroEstado.getSelectedItem() != "Todos") {
            String e = (String) filtroEstado.getSelectedItem().toString();
            if (e != null && !e.equals(acomodacao.getEstado().toString())) {
                return false;
            }
        }
        if (filtroPorte.getSelectedItem()!=null && filtroPorte.getSelectedItem() != "Todos") {
            String p = (String) filtroPorte.getSelectedItem().toString();
            if (p != null && !p.equals(acomodacao.getDimensao().toString())) {
                return false;
            }
        }
        if (filtroEspecie.getSelectedItem()!=null && filtroEspecie.getSelectedItem() != "Todos") {
            String es = (String) filtroEspecie.getSelectedItem().toString();
            if (es != null && !es.equals(acomodacao.getEspecie().toString())) {
                return false;
            }
        }
        return true;
    }

    private void preencherAcomodacoes() {
        acomodacoesStatus.setText("");
        Set<Acomodacao> aco = BancoDeDados.getInstance().getAcomodacoes();
        Iterator<Acomodacao> acomodacoes = aco.iterator();
        while (acomodacoes.hasNext()) {

            Acomodacao acomodacao = acomodacoes.next();
            if (checarNoFiltro(acomodacao)) {
                acomodacoesStatus.setText(acomodacoesStatus.getText()
                        + acomodacao.getNum() + " : " + acomodacao.getDimensao() + "; "
                        + acomodacao.getEstado() + "; ");
                if (acomodacao.getEstado() == AcomodacaoEstado.emUso) {
                    acomodacoesStatus.setText(acomodacoesStatus.getText()
                            + acomodacao.getEstadia().getAnimal().getNome() + "\n----------------------------\n");
                } else {
                    acomodacoesStatus.setText(acomodacoesStatus.getText() + "\n----------------------------\n");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        acomodacoesStatus = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        filtroEspecie = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filtroPorte = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        filtroEstado = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Acomodações");

        jScrollPane2.setViewportView(acomodacoesStatus);

        jLabel2.setText("Filtrar por: ");

        filtroEspecie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtroEspecie.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroEspecieItemStateChanged(evt);
            }
        });
        filtroEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroEspecieActionPerformed(evt);
            }
        });

        jLabel3.setText("Especie:");

        jLabel4.setText("Porte:");

        filtroPorte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtroPorte.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroPorteItemStateChanged(evt);
            }
        });
        filtroPorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroPorteActionPerformed(evt);
            }
        });

        jLabel5.setText("Estado:");

        filtroEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtroEstado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filtroEstadoItemStateChanged(evt);
            }
        });
        filtroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filtroPorte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filtroEspecie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filtroEstado, javax.swing.GroupLayout.Alignment.TRAILING, 0, 187, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filtroEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtroPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(filtroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filtroEspecieItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroEspecieItemStateChanged
        preencherAcomodacoes();
    }//GEN-LAST:event_filtroEspecieItemStateChanged

    private void filtroPorteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroPorteItemStateChanged
        preencherAcomodacoes();
    }//GEN-LAST:event_filtroPorteItemStateChanged

    private void filtroEstadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filtroEstadoItemStateChanged
        preencherAcomodacoes();
    }//GEN-LAST:event_filtroEstadoItemStateChanged

    private void filtroPorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroPorteActionPerformed
        preencherAcomodacoes();
    }//GEN-LAST:event_filtroPorteActionPerformed

    private void filtroEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroEspecieActionPerformed
        preencherAcomodacoes();
    }//GEN-LAST:event_filtroEspecieActionPerformed

    private void filtroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroEstadoActionPerformed
        preencherAcomodacoes();
    }//GEN-LAST:event_filtroEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAcomodacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAcomodacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAcomodacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAcomodacaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConsultaAcomodacaoView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane acomodacoesStatus;
    private javax.swing.JComboBox filtroEspecie;
    private javax.swing.JComboBox filtroEstado;
    private javax.swing.JComboBox filtroPorte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
