/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lp.view;

import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;
import lp.HotelAnimais.Animal;
import lp.HotelAnimais.Especie;
import lp.HotelAnimais.Porte;
import lp.HotelCachorros.Persistencia.BancoDeDados;
import lp.view.Logic.SalvaArquivo;

/**
 *
 * @author vanderson
 */
public class RelatorioView extends javax.swing.JFrame {

    /**
     * Creates new form Relatorio
     */
    public RelatorioView() {
        initComponents();
        preencherFiltros();
        preencheRelatorio();
        
    }

    private boolean checarNoFiltro(Animal animal) {
        if (filtroEspecie.getSelectedItem() != null
                && filtroEspecie.getSelectedItem() != "Todos") {
            String e = (String) filtroEspecie.getSelectedItem().toString();
            if (e != null && !e.equals(animal.getEspecie().toString())) {
                return false;
            }
        }
        if (filtroPorte.getSelectedItem() != null
                && filtroPorte.getSelectedItem() != "Todos") {
            String e = (String) filtroPorte.getSelectedItem().toString();
            if (e != null && !e.equals(animal.getPorte().toString())) {
                return false;
            }
        }
        if (formaRelatorio.getSelectedIndex() == 0
                && BancoDeDados.getInstance().getEstadia(animal) == null) {
            return false;
        }
        return true;
    }

    private void preencheRelatorio() {
        relatorio.setText("");
        Set<Animal> ani = BancoDeDados.getInstance().getAnimais();
        Iterator<Animal> animais = ani.iterator();
        while (animais.hasNext()) {

            Animal animal = animais.next();
            if (checarNoFiltro(animal)) {
                relatorio.setText(relatorio.getText() + "\n"
                        + "Nome: " + animal.getNome() + "\n"
                        + "Altura: " + animal.getAltura() + "\n"
                        + "Comprimento: " + animal.getComprimento() + "\n"
                        + "Responsável: " + animal.getDono().getNome() + " Tel: " + animal.getDono().getTele() + "\n"
                        + "Segundo Resp.:" + animal.getResponsavel2().getNome() + " Tel: " + animal.getResponsavel2().getTele() + "\n"
                        + "Especie: " + animal.getEspecie() + "\n"
                        + "Porte: " + animal.getPorte() + "\n"
                        + "\n");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formaRelatorio = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filtroEspecie = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        filtroPorte = new javax.swing.JComboBox();
        salvarBotao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        relatorio = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Relatório de: ");

        formaRelatorio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Animais hospedados", "Animais cadastrados" }));
        formaRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaRelatorioActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtrar por:");

        jLabel3.setText("Especies:");

        filtroEspecie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtroEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroEspecieActionPerformed(evt);
            }
        });

        jLabel4.setText("Porte:");

        filtroPorte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filtroPorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroPorteActionPerformed(evt);
            }
        });

        salvarBotao.setText("Salvar");
        salvarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBotaoActionPerformed(evt);
            }
        });

        relatorio.setColumns(20);
        relatorio.setRows(5);
        jScrollPane1.setViewportView(relatorio);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(formaRelatorio, 0, 268, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel4)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(filtroEspecie, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(filtroPorte, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(salvarBotao)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(formaRelatorio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(filtroEspecie, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel4)
                    .add(filtroPorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(salvarBotao)
                .add(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formaRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaRelatorioActionPerformed
        preencheRelatorio();
    }//GEN-LAST:event_formaRelatorioActionPerformed

    private void filtroEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroEspecieActionPerformed
        preencheRelatorio();
    }//GEN-LAST:event_filtroEspecieActionPerformed

    private void salvarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBotaoActionPerformed
        String input = JOptionPane.showInputDialog("Digite o nome do arquivo:");
        new SalvaArquivo(input,relatorio.getText());
        JOptionPane.showMessageDialog(null, "Salvo com sucesso!");
    }//GEN-LAST:event_salvarBotaoActionPerformed

    private void filtroPorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroPorteActionPerformed
        preencheRelatorio();
    }//GEN-LAST:event_filtroPorteActionPerformed

    private void preencherFiltros() {
        preencherFiltroEspecie();
        preencherFiltroPorte();

    }

    private void preencherFiltroEspecie() {
        filtroEspecie.removeAllItems();
        filtroEspecie.addItem("Todos");
        for (Especie e : Especie.values()) {
            filtroEspecie.addItem(e);
        }
    }

    private void preencherFiltroPorte() {

        filtroPorte.removeAllItems();
        filtroPorte.addItem("Todos");
        for (Porte e : Porte.values()) {
            filtroPorte.addItem(e);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox filtroEspecie;
    private javax.swing.JComboBox filtroPorte;
    private javax.swing.JComboBox formaRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea relatorio;
    private javax.swing.JButton salvarBotao;
    // End of variables declaration//GEN-END:variables
}
